### ISSUE TITLE
Constructor-based injection usage

### ISSUE THREAD

**Issue by kmandalas** [tripsta/spring-boot-starter-kit#9]
Consider replacing field injection with constructor-based for mandatory depencencies

**Comment by Thodoras** [comment]
What will be the benefit?

**Comment by kmandalas** [comment]
It's simply a more strict/explicit auto-wiring method recommended by Spring for mandatory dependencies. This way the container initialization will fail at start-up if for some reason a mandatory bean is missing. Other way is will be passed as null and null-pointer will occur upon usage. It's a more strict and fail-fast approach.

**Comment by Thodoras** [comment]
That's an argument we were looking for when were implementing it. We chose field injection back then as there were more examples and to be honest the code looked more compact.

**Comment by kmandalas** [comment]
Thanks for the feedback. You may label it as a question and close.

**Comment by Thodoras** [comment]
That's an argument we were looking for when were implementing it. We chose
field injection then because there where more examples and to be honest
code looked more compact.
